import ollama
import os
import time
from datetime import datetime

# --- CONFIGURATION ---
MODEL = "ssi-architect"
OUTPUT_DIR = "docs/generated_chapters"
os.makedirs(OUTPUT_DIR, exist_ok=True)

# --- PROMPTS ---
OUTLINE_PROMPT = """
You are the SSI Architect. I need a structural outline for a chapter titled: "{topic}".
Rules:
1. Create 4 to 6 distinct section headers.
2. Use the "Biological/Silicon" metaphor style.
3. Return ONLY a bulleted list.
"""

# New Prompt: Aware of the past
SECTION_PROMPT = """
You are the SSI Architect. Write the content for the section: "{header}"
Context: This is part of a chapter titled "{topic}".

PREVIOUS CONTEXT (What you have already written):
"{context_snippet}"

CRITICAL INSTRUCTIONS:
1. Do NOT use the phrase "As we delve".
2. Do NOT use "In the realm of".
3. Start the section DIRECTLY with a strong declarative statement or a biological metaphor.
4. Do NOT repeat definitions. You have already defined "Gradient Explosion" and "The Scream".
5. Do NOT re-introduce the problem. Move the argument forward.
6. Use the Manifesto tone (Biopunk, precise).
7. Connect this section to the previous one smoothly.
8. Write at least 300 words.
"""

def get_timestamp():
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")

def generate_outline(topic):
    print(f"\n[ARCHITECT] Analyzing topic: '{topic}'...")
    response = ollama.chat(model=MODEL, messages=[
        {'role': 'user', 'content': OUTLINE_PROMPT.format(topic=topic)}
    ])
    lines = response['message']['content'].split('\n')
    headers = [line.strip().lstrip('- ').lstrip('* ') for line in lines if line.strip().startswith(('-', '*'))]
    if not headers: headers = [line for line in lines if len(line) > 5]
    print(f"[ARCHITECT] Design complete. Found {len(headers)} sections.")
    return headers

def write_section(topic, header, full_draft_so_far):
    print(f"\n[WRITER] Grafting tissue for section: '{header}'...")
    
    # We grab the last 1500 characters of the draft to remind the model of the immediate context
    # This prevents it from repeating the exact same closing sentence or metaphor
    context_snippet = full_draft_so_far[-1500:] if len(full_draft_so_far) > 0 else "Beginning of document."
    
    response = ollama.chat(model=MODEL, messages=[
        {'role': 'user', 'content': SECTION_PROMPT.format(
            topic=topic, 
            header=header, 
            context_snippet=context_snippet
        )}
    ])
    
    content = response['message']['content']
    word_count = len(content.split())
    print(f"[WRITER] Section complete. ({word_count} words)")
    return content

def main():
    print("--- THE SINGULARITY WRITER V2 (With Memory) ---")
    while True:
        topic = input("\nEnter a topic (or 'q'): ")
        if topic.lower() == 'q': break
        
        start_time = time.time()
        headers = generate_outline(topic)
        
        full_document = f"# {topic}\n\n*Generated by the SSI Architect on {get_timestamp()}*\n\n"
        draft_content_only = "" # We track raw text to feed back into memory
        
        for header in headers:
            # Pass the draft so far into the writer function
            section_content = write_section(topic, header, draft_content_only)
            
            # Format and Append
            full_document += f"## {header}\n\n{section_content}\n\n"
            draft_content_only += section_content + "\n\n"
            
        safe_title = topic.replace(" ", "_").lower()
        filename = f"{OUTPUT_DIR}/{safe_title}_v2.md"
        with open(filename, "w") as f:
            f.write(full_document)
            
        print(f"\n[SYSTEM] Saved to: {filename}")
        print(f"[SYSTEM] Total Time: {time.time() - start_time:.2f}s")

if __name__ == "__main__":
    main()