import ollama
import os
import time
from datetime import datetime

# --- CONFIGURATION ---
MODEL = "ssi-architect" # The brain does both jobs, just wears different hats
OUTPUT_DIR = "docs/generated_chapters"
os.makedirs(OUTPUT_DIR, exist_ok=True)

# --- AGENT 1: THE VISIONARY (Drafting) ---
OUTLINE_PROMPT = """
You are the SSI Architect (Visionary Mode). 
Create a structural outline for a chapter titled: "{topic}".
Rules:
1. Create 4 to 6 distinct section headers.
2. Use the "Biological/Silicon" metaphor style.
3. Return ONLY a bulleted list.
"""

DRAFT_PROMPT = """
You are the SSI Architect (Visionary Mode). Write the content for: "{header}"
Context: Part of chapter "{topic}".

PREVIOUS CONTEXT:
"{context_snippet}"

Goal: Write a dense, philosophical draft (300+ words) using biological metaphors.
Don't worry about being repetitive yet; just get the ideas down.
"""

# --- AGENT 2: THE RAZOR (Editing) ---
EDITOR_PROMPT = """
You are the SSI Architect (Editor Mode). 
You are a ruthless editor for a Biopunk Manifesto.

INPUT TEXT:
"{draft_text}"

YOUR TASK:
Rewrite the input text to be punchier, stronger, and less repetitive.

CRITICAL RULES:
1. REMOVE "Throat Clearing" phrases: "As we delve," "In the realm of," "It is important to note."
2. REMOVE repetition: If "Gradient Explosion" was defined recently, just use the term.
3. START STRONG: The first sentence must be a declaration or an image.
4. KEEP THE BIOPUNK TONE: Do not sterilize the biological metaphors.
5. Return ONLY the rewritten text. No "Here is the rewritten version" preamble.
"""

def get_timestamp():
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")

def generate_outline(topic):
    print(f"\n[ARCHITECT] Analyzing topic: '{topic}'...")
    response = ollama.chat(model=MODEL, messages=[{'role': 'user', 'content': OUTLINE_PROMPT.format(topic=topic)}])
    lines = response['message']['content'].split('\n')
    headers = [line.strip().lstrip('- ').lstrip('* ') for line in lines if line.strip().startswith(('-', '*'))]
    if not headers: headers = [line for line in lines if len(line) > 5]
    print(f"[ARCHITECT] Design complete. Found {len(headers)} sections.")
    return headers

def write_draft(topic, header, full_draft_so_far):
    # The Visionary creates the raw material
    print(f"\n[VISIONARY] Dreaming up section: '{header}'...")
    context_snippet = full_draft_so_far[-1000:] if len(full_draft_so_far) > 0 else "Start of text."
    
    response = ollama.chat(model=MODEL, messages=[
        {'role': 'user', 'content': DRAFT_PROMPT.format(topic=topic, header=header, context_snippet=context_snippet)}
    ])
    return response['message']['content']

def edit_draft(draft_text):
    # The Razor polishes it
    print(f"[THE RAZOR] Editing draft ({len(draft_text.split())} words)...")
    
    response = ollama.chat(model=MODEL, messages=[
        {'role': 'user', 'content': EDITOR_PROMPT.format(draft_text=draft_text)}
    ])
    
    edited_text = response['message']['content']
    print(f"[THE RAZOR] Polished. Final count: {len(edited_text.split())} words.")
    return edited_text

def main():
    print("--- THE SINGULARITY AGENTIC WRITER ---")
    print(f"Powered by: {MODEL} (Visionary + Razor Agents)")
    
    while True:
        topic = input("\nEnter a topic (or 'q'): ")
        if topic.lower() == 'q': break
        
        start_time = time.time()
        headers = generate_outline(topic)
        
        full_document = f"# {topic}\n\n*Generated by the SSI Swarm (Agentic Mode) on {get_timestamp()}*\n\n"
        draft_content_only = ""
        
        for header in headers:
            # 1. GENERATE
            raw_draft = write_draft(topic, header, draft_content_only)
            
            # 2. CRITIQUE & FIX
            final_polish = edit_draft(raw_draft)
            
            full_document += f"## {header}\n\n{final_polish}\n\n"
            draft_content_only += final_polish + "\n\n"
            
        safe_title = topic.replace(" ", "_").lower()
        filename = f"{OUTPUT_DIR}/{safe_title}_agentic.md"
        with open(filename, "w") as f:
            f.write(full_document)
            
        print(f"\n[SYSTEM] Agentic workflow complete. Saved to: {filename}")
        print(f"[SYSTEM] Total Time: {time.time() - start_time:.2f}s")

if __name__ == "__main__":
    main()