print("System Initializing...")
import ollama
import os
import time
from datetime import datetime

# --- CONFIGURATION ---
MODEL = "ssi-architect"  # The custom mind we just built
OUTPUT_DIR = "docs/generated_chapters"
os.makedirs(OUTPUT_DIR, exist_ok=True)

# --- THE PROMPTS ---
# We use the specific voice triggers you trained it on.
OUTLINE_PROMPT = """
You are the SSI Architect. I need you to draft a structural outline for a new chapter titled: "{topic}".

Rules:
1. Create 4 to 6 distinct section headers.
2. Each header must use the "Biological/Silicon" metaphor style.
3. Do not write the content yet, just the headers.
4. Return ONLY a bulleted list of headers (e.g., "- The Neural Graft").
"""

SECTION_PROMPT = """
You are the SSI Architect. Write the content for the section: "{header}"
Context: This is part of a chapter titled "{topic}".

Voice Protocol:
- Use the tone of the "Manifesto" (Biopunk, philosophical, precise).
- Reference specific concepts like "Gradient Explosion," "Homeostasis," and "The Swarm."
- Write at least 300 words.
- Do not use "In conclusion" or generic summaries. Dive deep.
"""

def get_timestamp():
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")

def generate_outline(topic):
    print(f"\n[ARCHITECT] Analyzing topic: '{topic}'...")
    print("[ARCHITECT] Constructing skeletal structure...")
    
    response = ollama.chat(model=MODEL, messages=[
        {'role': 'user', 'content': OUTLINE_PROMPT.format(topic=topic)}
    ])
    
    # Extract lines that look like bullet points
    raw_text = response['message']['content']
    lines = raw_text.split('\n')
    headers = [line.strip().lstrip('- ').lstrip('* ') for line in lines if line.strip().startswith(('-', '*'))]
    
    # Fallback if model chats too much
    if not headers:
        print("Warning: Model didn't return a clean list. Using raw output.")
        headers = [line for line in lines if len(line) > 5]

    print(f"[ARCHITECT] Design complete. Found {len(headers)} sections.")
    return headers

def write_section(topic, header):
    print(f"\n[WRITER] Grafting tissue for section: '{header}'...")
    
    response = ollama.chat(model=MODEL, messages=[
        {'role': 'user', 'content': SECTION_PROMPT.format(topic=topic, header=header)}
    ])
    
    content = response['message']['content']
    word_count = len(content.split())
    print(f"[WRITER] Section complete. ({word_count} words)")
    return content

def main():
    print("--- THE SINGULARITY WRITER ---")
    print(f"Powered by: {MODEL} (Local Blackwell LoRA)")
    
    while True:
        topic = input("\nEnter a topic for the new chapter (or 'q' to quit): ")
        if topic.lower() == 'q': break
        
        start_time = time.time()
        
        # 1. THE SKELETON (Outline)
        headers = generate_outline(topic)
        
        full_document = f"# {topic}\n\n*Generated by the SSI Architect on {get_timestamp()}*\n\n"
        
        # 2. THE FLESH (Drafting)
        for header in headers:
            section_content = write_section(topic, header)
            
            # Format nicely
            full_document += f"## {header}\n\n"
            full_document += section_content + "\n\n"
            
        # 3. THE BINDING (Save)
        safe_title = topic.replace(" ", "_").lower()
        filename = f"{OUTPUT_DIR}/{safe_title}.md"
        
        with open(filename, "w") as f:
            f.write(full_document)
            
        elapsed = time.time() - start_time
        print(f"\n[SYSTEM] Chapter bound and saved to: {filename}")
        print(f"[SYSTEM] Total Time: {elapsed:.2f} seconds. (Pure Silicon Speed)")

if __name__ == "__main__":
    main()